apiVersion: apps/v1
kind: Deployment
metadata:
  name: application
  labels:
    app: employees
    component: frontend
spec:
  selector:
    matchLabels:
      app: employees
      component: frontend
  replicas: 3
  template:
    metadata:
      labels:
        app: employees
        component: frontend
    spec:
      containers:
      - name: application-container
        image: 385826816562.dkr.ecr.us-east-1.amazonaws.com/application-repo:latest
        env:
        - name: DBPWD
          value: pass
        - name: DBUSER
          value: root
        - name: DBHOST
          value: "mysql.database.svc.cluster.local"
        - name: DBPORT
          value: "3306"
        ports:
        - containerPort: 8080