apiVersion: apps/v1
kind: Deployment
metadata:
  name: application
  labels:
    app.kubernetes.io/name: employees
    app.kubernetes.io/component: frontend
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: employees
      app.kubernetes.io/component: frontend
  replicas: 3
  template:
    metadata:
      labels:
        app.kubernetes.io/name: employees
        app.kubernetes.io/component: frontend
    spec:
      containers:
      - name: application-container
        image: 385826816562.dkr.ecr.us-east-1.amazonaws.com/application-repo:latest
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: pass
        ports:
        - containerPort: 3306
    imagePullSecrets:
        - name: cred