apiVersion: v1
kind: Pod
metadata:
  name: application
  labels:
    app.kubernetes.io/name: employees
    app.kubernetes.io/component: frontend
spec:
  containers:
    - name: application-container
      image: 385826816562.dkr.ecr.us-east-1.amazonaws.com/application-repo:latest
      env:
        - name: DBPWD
          value: pass
        - name: DBUSER
          value: root
        - name: DBHOST
          value: "mysql.backend.svc.cluster.local"
        - name: DBPORT
          value: "3306"
      ports:
        - containerPort: 8080
  imagePullSecrets:
    - name: regcred