apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 3
  template:
    metadata:
      labels:
        app: mysql
        component: backend
    spec:
      containers:
      - name: mysql-containers
        image: 385826816562.dkr.ecr.us-east-1.amazonaws.com/database-repo:latest
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: pass
        ports:
        - containerPort: 3306
