apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  containers:
    - name: mysql-container
      image: 385826816562.dkr.ecr.us-east-1.amazonaws.com/database-repo:latest
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: pass
      ports:
        - containerPort: 3306