apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mysql
  labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/component: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mysql
        app.kubernetes.io/component: backend
    spec:
      containers:
        - name: mysql-container
          image: 385826816562.dkr.ecr.us-east-1.amazonaws.com/database-repo:latest
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: pass
          ports:
            - containerPort: 3306
      imagePullSecrets:
          - name: cred